### ISSUE TITLE
touchegg-gui: use() calls in global scope

### ISSUE THREAD

**Issue by ethus3h** [stintel/gentoo-overlay#1]
touchegg-gui-1.1.1.ebuild could be changed to something like this: https://github.com/ethus3h/wreathe-overlay/blob/master/x11-misc/touchegg-gui/touchegg-gui-1.1.1.ebuild

Thanks for maintaining the overlay! :D

**Comment by ethus3h** [comment]
Thanks! :)

**Comment by stintel** [comment]
You're welcome, thanks for reporting. I must have missed it in the GitHub notification spam, or I'd fixed it sooner.
